<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="api.tests.test_view_auth.BadUsesOfAuthHeaderTestCase-20250630054001" tests="2" file="api/tests/test_view_auth.py" time="0.001" timestamp="2025-06-30T05:40:51" failures="0" errors="0" skipped="0">
	<testcase classname="api.tests.test_view_auth.BadUsesOfAuthHeaderTestCase" name="test_get_unencode_value" time="0.001" timestamp="2025-06-30T05:40:51" file="advisor/api/tests/test_view_auth.py" line="431"/>
	<testcase classname="api.tests.test_view_auth.BadUsesOfAuthHeaderTestCase" name="test_system_and_user_auth" time="0.001" timestamp="2025-06-30T05:40:51" file="advisor/api/tests/test_view_auth.py" line="439"/>
</testsuite>
