<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="api.tests.test_cert_auth.CertAuthTestCase-20250630054001" tests="8" file="api/tests/test_cert_auth.py" time="0.236" timestamp="2025-06-30T05:40:05" failures="0" errors="0" skipped="0">
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_auth_failures" time="0.012" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="46"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_get_non_owned_system" time="0.037" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="116"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_get_non_owned_system_reports" time="0.014" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="123"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_list_system_satellite" time="0.037" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="87"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_list_system_self_owned" time="0.043" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="104"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_rule_list" time="0.054" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="132"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_systems_stats" time="0.018" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="148"/>
	<testcase classname="api.tests.test_cert_auth.CertAuthTestCase" name="test_topic_list" time="0.020" timestamp="2025-06-30T05:40:05" file="advisor/api/tests/test_cert_auth.py" line="170"/>
</testsuite>
